DROP TABLE IF EXISTS `modelutils_auth`;
CREATE TABLE `modelauth`(
  `id`         INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user`    INT(10) UNSIGNED DEFAULT NULL,
  `uuid`      CHAR(32) NOT NULL,
  `logged`  TINYINT(1) NOT NULL DEFAULT 0,
  `date`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`id_user`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;