/**
 * @author Hector Menendez <h@cun.mx>
 * @licence http://etor.mx/licence.txt
 * @updated 2011/SEP/16 03:36 Fixed error, removed AUTO_INCREMENT declaration.
 * @created 2011/SEP/03 03:46
 */
DROP TABLE IF EXISTS `language`;
CREATE TABLE `language`(
  `id`       CHAR(2) NOT NULL,
  `name` VARCHAR(12) NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `language` (`id`,`name`) VALUES
  ('es','Español'),
  ('en','English');

/**
 * @author Hector Menendez <h@cun.mx>
 * @licence http://etor.mx/licence.txt
 * @created 2011/SEP/03 03:55
 */
DROP TABLE IF EXISTS `category`;
CREATE TABLE `category` (
  `id`         INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang`      CHAR(2) NOT NULL,
  `class` VARCHAR(22) NOT NULL,
  `name`  VARCHAR(22) NOT NULL,
  `url`   VARCHAR(22) NOT NULL,
  `keyw` VARCHAR(300) NOT NULL,
  `desc` VARCHAR(300) NOT NULL,
  PRIMARY KEY(`id`),
  INDEX(`lang`),
  INDEX(`class`),
  INDEX(`url`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
INSERT INTO `category` (`lang`, `class`, `name`, `url`, `keyw`, `desc`) VALUES
  ('es', 'inyectable', 'Inyectable', 'inyectable', ' ', ' '),
  ('en', 'inyectable', 'Injectable', 'injectable', ' ', ' '),
  ('es', 'nuevo'     , 'Nuevo'     , 'nuevo'     , ' ', ' '),
  ('en', 'nuevo'     , 'New'       , 'new'       , ' ', ' ');


/**
 * @author Hector Menendez <h@cun.mx>
 * @licence http://etor.mx/licence.txt
 * @updated 2011/SEP/16 03:37 Fixed error, removed `class` as UNIQUE.
 * @created 2011/SEP/03 04:09
 */
DROP TABLE IF EXISTS `product`;
CREATE TABLE `product`(
  `id`         INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang`       CHAR(2) NOT NULL,
  `categ`  VARCHAR(22) NOT NULL,
  `class`  VARCHAR(44) NOT NULL,
  `name`   VARCHAR(66) NOT NULL,
  `cont`    MEDIUMTEXT NOT NULL,
  `keyw`  VARCHAR(300) NOT NULL,
  `desc`  VARCHAR(300) NOT NULL,
  `urln`  VARCHAR(128) NOT NULL, /* url safe name     */
  `urlc`   VARCHAR(22) NOT NULL, /* url safe category */
  `urli`  VARCHAR(512) NOT NULL, /* url image         */
  `price` DECIMAL(9,2) NOT NULL DEFAULT 0,
  PRIMARY KEY(`id`),
  INDEX(`class`),
  INDEX(`lang`),
  INDEX(`categ`),
  INDEX(`urln`),
  INDEX(`urlc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
INSERT INTO `product` (`lang`, `categ`, `class`, `name`, `keyw`, `desc`, `urln`, `urlc`, `price`, `urli`, `cont`) VALUES
  ('en', 'inyectable', 'testosterone-p100'  , 'Testosterone P100'            , ' ', ' ', 'testosterone-p100'            , 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-p100.jpg'            , '**Testosterone Propionate 100mg.**\n\n**Testosterone Propionate** despite not having a long duration in the system, it is used by many athletes in the cut and lined phase and in volume cycles. Its effects from day one of its intake, it''s highly androgenic.\n\nRecommended doses: 100mg. to 200mg. every third day.'),
  ('en', 'inyectable', 'trenb-100a'         , 'Trenb 100 A'                  , ' ', ' ', 'trenb-100-a'                  , 'injectable', '0.00', '/palmera/pub/en/injectable/trenb-100-a.jpg'                  , '**Trenbolone Acetate 100mg**\n\n**Trenbolone Acetate** is an extremely Sorong with a lot of anabolic activity, in very few days you can see a fast strength acumulation and muscular size, thus leaving a hard defined aspect. It is used a lot with testosterones, dianabol an other agents. Promotes proteic synthesis and appetite increase.\n\n**Trembolone Acetate** does not produce liquid retention nor does it aromatize.\n\nRecommended doses 75mg. to 200mg. per week.'),
  ('en', 'inyectable', 'testosterone-phenyl', 'Testosterone Phenylpropionate', ' ', ' ', 'testosterone-phenylpropionate', 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-phenylpropionate.jpg', '**Testosterone Phenyl Propionate 100 mg.**\n\n**Phenyl Propionate** is an injectable testosterone with more than 3 weeks duration, its usage is more common among weight lifters and athletes for the potencialization of a high performance when it is combined with other anabolics you get excellent results in muscular mass gain. \nThis testosterone is attributed with similar effects to the nandrolones.\n\nRecommended dose of 100 mg. to 300 mg. per week.'),
  ('en', 'inyectable', 'trenb-100e'         , 'Trenb 100 E'                  , ' ', ' ', 'trenb-100-e'                  , 'injectable', '0.00', '/palmera/pub/en/injectable/trenb-100-e.jpg'                  , '**Trenbolone Enanthate 100 mg.**\n\n**Trenbolone Enanthate** is a prolongad action inyectable steroid. It has positive effects promoting the protein synthesis, making a better absorption. It is an appetite stimulant, it has a high benefit diminishing the fat deposits. It is proven that Trenbolone enanthate is a product that generates strength and size progressing in the body tissue construction, this way generating an impressive amount. \n\nThis ester does not produce liquid retention nor aromatization. \n\nRecommended doses 75 mg. to 200 mg. per week'),
  ('en', 'inyectable', 'testosterone-b250'  , 'Testosterone B250'            , ' ', ' ', 'testosterone-b250'            , 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-b250.jpg'            , '**Testosterone Propionate** 30mg\n**Testosterone Phenylpropionate** 60mg\n**Testosterone Isocaproate** 60mg\n**Testosterone Caproate** 100mg\n\nThis testosterone mixtureis a combination of short and long effects in the testosterone levels in the system, to maintain a better level and a much better increase of muscular mass increasing the red globules and a significative quality in terms of energy, strength and size. \n\nRecommended doses of 250 mg. to 500 mg.  per week.'),
  ('en', 'inyectable', 'primobolan-d100'    , 'Primobolan D100'              , ' ', ' ', 'primobolan-d100'              , 'injectable', '0.00', '/palmera/pub/en/injectable/primobolan-d100.jpg'              , '**Enanthate Methenolone** 100 mg.\n\n**Primobolan (Enantate Methenolone)** is a product that doesn’t produce any aromatization, is a long lasting product and is a extremely safe steroid. It is used by most of the builders between steroid cycles to maintain their muscular mass.\n\nRecommended doses 100 mg. to 400 mg. per week'),
  ('en', 'inyectable', 'testosterone-m250'  , 'Testosterone M250'            , ' ', ' ', 'testosterone-m250'            , 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-m250.jpg'            , '**Testosterone Phenyl Propionate** 125 mg.\n**Testosterone Isohexanoate** 125 mg.\n\nIt is a mixture of two testosterones combined for an improvement in the testosterone levels in the system, producing a high and pronounced muscle and force increase.\n\nRecommended Dosesof 250 mg to 500 mg per week.'),
  ('en', 'inyectable', 'boldenone-200'      , 'Boldenone 200'                , ' ', ' ', 'boldenone-200'                , 'injectable', '0.00', '/palmera/pub/en/injectable/boldenone-200.jpg'                , '**Boldenone Undecylenate** 200 mg.\n\n**Boldenone Undecylenate** is a very effective inyectable anabolic of veterinarian usage. This compound is mildly androgenic, applicable through a shot a week. Because it has an long lasting life in average, with boldenone undecylenate you wil lnotice appetite increpase, a quality muscular mass and a notable definition because it doesnt produce liquid retention. Used generally with testosterones, trenbolone and winstrol for bigger gain and quality. \n\nRecommended doses 200 mg. to 600 mg. per week.'),
  ('en', 'inyectable', 'testosterone-c250'  , 'Testosterone C250'            , ' ', ' ', 'testosterone-c250'            , 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-c250.jpg'            , '**Testosterone Cypionate 250** mg.\n\n**Testosterone Cypionate** is a highly Androgeinic Injectable ester. With this testosterone you can obtain a considerable muscular mass gain and strength with a high degree of liquid retention, it can produce easily ginecomasty because the testosterone converts easily the estrogens. This ester is injectable once a week to maintain the cypionate levels in the system.\n\nThis testosterone ester remains in the system for a longer period of time.\n\nRecommended doses 200 mg. to 600 mg. per week. '),
  ('en', 'inyectable', 'decadurabolin-250'  , 'Deca Durabolin 250'           , ' ', ' ', 'deca-durabolin-250'           , 'injectable', '0.00', '/palmera/pub/en/injectable/deca-durabolin-250.jpg'           , '**Nandrolone Decanoate** 250 mg.\n\n**Nandrolone Decanoate** Is an inyectable compound that with out a doubt mg per mg has a lot of positive effects for muscular mass and proteic synthesis, appetite stimulation, red globules production and increase of bone density. nandrolone decanoate is an anabolic that in high doses it can be highly androgenic. It is used by many athletes with muscular mass gain in mind, almost always in combination with testosterones. With this compound you can store more nitrogen than what is released and with a positive balance in the nitrogen is synonym of muscular growth because the cells can assimilate more protein quantities. nandrolone decanoate mantains a muscular tissue repair healing temporarily all the aches.\n\nThis compound is detectable for more than a year after its administration.\n\nRecommended doses 200 mg. to 600 mg. per week'),
  ('en', 'inyectable', 'testoviron-300'     , 'Testoviron 300'               , ' ', ' ', 'testoviron-300'               , 'injectable', '0.00', '/palmera/pub/en/injectable/testoviron-300.jpg'               , '**Testosterone Propionate** 112 mg.\n**Testosterone Enanthate** 188 mg.\n\n**Testoviron** is a injectable mixture of 2 testosterones (**Enanthate**, **Propionate**) the propionate with a rapid action and the enanthate with a 2 to 3 weeks duration, these testosterones produce a high estrogenic level because it converts the testosterone in estrogen easily producing a great liquid retention, strength and muscular size, the testoviron is used in cycles to obtain bigger size maintaining a perfect level of testosterone and increasing red globules, with this compound a ginecomasty can develop as well as other secondary effects.\n\nRecommended Doses of 200 mg to 600 mg per week.'),
  ('en', 'inyectable', 'decadurobalin-300'  , 'Deca Durabolin 300'           , ' ', ' ', 'deca-durabolin-300'           , 'injectable', '0.00', '/palmera/pub/en/injectable/deca-durabolin-300.jpg'           , '**Nandrolone Decanoate** 300 mg.\n\n**Nandrolone Decanoate** Is an inyectable compound that with out a doubt mg per mg has a lot of positive effects for muscular mass and proteic synthesis, appetite stimulation, red globules production and increase of bone density. nandrolone decanoate is an anabolic that in high doses it can be highly androgenic. It is used by many athletes with muscular mass gain in mind, almost always in combination with testosterones. With this compound you can store more nitrogen than what is released and with a positive balance in the nitrogen is synonym of muscular growth because the cells can assimilate more protein quantities. nandrolone decanoate mantains a muscular tissue repair healing temporarily all the aches.\n\nThis compound is detectable for more than a year alter its administration.\n\nRecommended doses 200 mg. to 600 mg. per week'),
  ('en', 'inyectable', 'testosterone-e300'  , 'Testosterone E300'            , ' ', ' ', 'testosterone-e300'            , 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-e300.jpg'            , '**Testosterone Enanthate** 300 mg.\n\n**Testosterone Enanthate** is one of the quintessentially most used steroids by weight lifters and athletes, this hormone has very positive effects in the muscular mass building, it is highly androgenic and a pronounceable visible liquid retention. This compound is used in males with hypogonadism (low testosterone levels) with this ester you get a better nitrogen retention in the synonym cells (muscular growth) and a repair of damaged tissues, an increase of red globules. It is used regularly with certain anabolics in cycles to obtain big amounts of muscular mass. \n\nRecommended Doses of 250 mg to 750 mg per week. '),
  ('en', 'inyectable', 'bestboldblend-200'  , 'Best Bold Blend 200'          , ' ', ' ', 'best-bold-blend-200'          , 'injectable', '0.00', '/palmera/pub/en/injectable/best-bold-blend-200.jpg'          , '**Boldenone Acetate** 30 mg.\n**Boldenone Propionate** 50 mg.\n**Boldenone Undecylenate** 100 mg.\n**Boldenone Cyclopentyl propionate (cypionate)** 20 mg.\n\n**Best Bold Blend 200** is a very efficient injectable anabolic of veterinarian usage. This compound is mildly androgenic. It’s applied with a shot per week because it has a long lasting life average. With this compound an increased of appetite is noticed, a quality muscular mass and a notable definition because it does not produce liquid retention. It is used mostly with testosterones, trenbolone and winstrol for a more quality gain\nThis compound is for body builders that love equiposes.\n\nThis blend will give a definition without liquid retention.\n\nDose of 200 mg. to 600 mg. per week.'),
  ('en', 'inyectable', 'sustanon-350'       , 'Sustanon 350'                 , ' ', ' ', 'sustanon-350'                 , 'injectable', '0.00', '/palmera/pub/en/injectable/sustanon-350.jpg'                 , '**Testosterone Acetate** 30 mg.\n**Testosterone Propionate** 60 mg.\n**Testosterone Phenylpropionate** 60 mg.\n**Testosterone Cypionate** 95 mg.\n**Testosterone Decanoate** 105 mg.\n\n**Sustanon 350** is an injectable mix. One of the most used by weight lifters and athletes, because it has been a perfect and lineal combination so that the body achieves perfect anabolic levels sustanon 350 is without a doubt a strength obtaining and solid size product. Its duration is much bigger than the testoviron keeping active from 3 to 4 weeks, this mix is used with oral products, dianabol, anadrol and some injectable, nandrolone decanoate and other agents.\n\nRecommended Doses of 350 mg. to 700 mg. per week.'),
  ('en', 'inyectable', 'best3nandrolona'    , 'Best 3nandrolona'             , ' ', ' ', 'best-3nandrolona'             , 'injectable', '0.00', '/palmera/pub/en/injectable/best-3nandrolona.jpg'             , '**Nandrolone Decanoate** 100 mg.\n**Nandrolone Phenylpropionate** 100 mg.\n**Nandrolone Undecanoate** 100 mg.\n\n**Best 3nandrolona** is the combination for a combined volume maximization for a better increase, obtaining a bigger appetite and nandrolon levels in the blood stream. Its usage can be combined with testosterone or others.\n\nRecommended Doses of 200 mg. to 600 mg\n'),
  ('en', 'inyectable', 'testosterone-400'   , 'Testosterone 400'             , ' ', ' ', 'testosterone-400'             , 'injectable', '0.00', '/palmera/pub/en/injectable/testosterone-400.jpg'             , '**Testosterone Propionate** 25 mg.\n**Testosterone Cypionate** 187 mg.\n**Testosterone Enanthate** 188 mg.\n\nThe **Testosterone 400** is an excellent mix, producing a perfect life cycle combination of each product in the blood system, although not lineal these testosterones increase drastically the red globules producing strength and noticeable weight increase. \n\nAs all testosterones it also produces a great liquid retention and high aromatization.\n\nRecommended Doses of 200 mg. to 800 mg. per week. '),
  ('en', 'inyectable', 'best3trend'         , 'Best 3Trend'                  , ' ', ' ', 'best-3trend'                  , 'injectable', '0.00', '/palmera/pub/en/injectable/best-3trend.jpg'                  , '**Trenabolone Acetate** 50 mg.\n**Trenbolone Hexahydrobenzylcarbonate** 50 mg.\n**Trenbolone Enanthate** 100 mg.\n\n**Best 3trend** this compound is the creation for a net mass gain and diminishing corporal fat, under this cycle you obtain the most cherished benefits and an impressive definition.\n\nRecommended doses 300 mg. per Week'),
  ('en', 'inyectable', 'bestblend-400'      , 'Best Blend 400'               , ' ', ' ', 'best-blend-400'               , 'injectable', '0.00', '/palmera/pub/en/injectable/best-blend-400.jpg'               , '**Trenbolone enanthate** 150 mg.\n**Testosterone Enanthate** 250 mg.\n\n**Best Blend 400** is a mix of trenbolone enanthate and testosterone enanthate. This blend produces a perfect ammount of quality muscle. Without a doubt is a very effective combination for a 5 to 8 kgs increase of muscular mass in just 6 weeks.\n\nRecommended Doses of 400 mg. to 800 mg. per week'),
  ('en', 'inyectable', 'bestblend-450'      , 'Best Blend 450'               , ' ', ' ', 'best-blend-450'               , 'injectable', '0.00', '/palmera/pub/en/injectable/best-blend-450.jpg'               , '**Trenbolone Enanthate** 150 mg.\n**Testosterone Enanthate** 250 mg.\n**Testosterone Propionate** 50 mg.\n\n**Best Blend 450** es una mezcla de dos testosteronas una de vida promedio corta (propionate) y otra de larga duracion (enanthate) que combinados con trembolone ofrece un nivel sumamente bueno de anabólicos en el sistema sanguíneo. Esta combinación es perfecta para la obtención de mucha masa bien definida y buena calidad con este compuesto se pueden obtener asta 8 kilos de masa en 6 semanas.\n\nDosis recomendadas de 450 mg. a 900 mg. por semana.'),
  ('en', 'inyectable', 'bestblend-500'      , 'Best Blend 500'               , ' ', ' ', 'best-blend-500'               , 'injectable', '0.00', '/palmera/pub/en/injectable/best-blend-500.jpg'               , '**Boldenone Undecylenate** 200 mg.\n**Testosterone Enanthate** 100 mg.\n**Testosterone Cypionate** 100 mg.\n**Trenbolone Enanthate** 100 mg.\n\n**Best Blend 500** is a blend of 4 compounds perfectly combined and linear. To add to the body an extreme amount of muscular mass and well defined size.\n\nRecommended Doses of 500 mg. to 1000 mg. per week.'),
  ('en', 'inyectable', 'bestblend-600'      , 'Best Blend 600'               , ' ', ' ', 'best-blend-600'               , 'injectable', '0.00', '/palmera/pub/en/injectable/best-blend-600.jpg'               , '**Testosterone Cypionate** 200 mg.\n**Boldenone Undecylenate** 200 mg.\n**Nandrolone Decanoate** 200 mg.\n\n**Best Blend 600** is a mix of excellent products that combine two anabolics and an androgenic to obtain a considerable weight increase. This compound is injectable one or twice a week according to your needs.\n\nRecommended doses from 600 mg. to 1200 mg. per week.'),
  ('es', 'inyectable', 'testosterone-p100'  , 'Testosterone P100'            , ' ', ' ', 'testosterone-p100'            , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-p100.jpg'            , '**Testosterone Propionate 100mg.**\n\n**Testosterone propionate** a pesar de no tener una larga duración en el sistema, es usado por muchos atletas en la fase de corte y rayado y en los ciclos de volumen, sus efectos aparecen desde el primer día de su aplicación y es altamente androgénico.\n\nDósis recomendadas: 100mg. a 200mg. cada tercer día.'),
  ('es', 'inyectable', 'trenb-100a'         , 'Trenb 100 A'                  , ' ', ' ', 'trenb-100-a'                  , 'inyectable', '0.00', '/palmera/pub/es/inyectable/trenb-100-a.jpg'                  , '**Trenbolone Acetate 100mg**\n\n**Trenbolone Acetate** es un esteroide sumamente fuerte con mucha actividad anabólica. En muy pocos días se puede ver rápida acumulación de fuerza y tamaño muscular, dando así un aspecto duro y definido. Es muy usada con testosteronas, dianabol y otros agentes, promueve la síntesis protéica y aumento del apetito.\n\nLa **Trembolone Acetate** no produce retención de liquidos ni aromatiza.\n\nDósis recomendadas de 75mg. a 200mg. por semana.\n'),
  ('es', 'inyectable', 'testosterone-phenyl', 'Testosterone Phenylpropionate', ' ', ' ', 'testosterone-phenylpropionate', 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-phenylpropionate.jpg', '**Testosterone Phenyl Propionate 100 mg.**\n\nEl **Phenyl Propionate** es una testosterona inyectable con una duración de mas de 3 semanas, su utilización mas común es por levantadores de pesas y atletas para potencialización de un alto rendimiento ya que en combinación con otros anabólicos se obtienen excelentes resultados en ganancia de masa muscular, a esta testosterone se le atribuyen similitudes con los efectos de las nandrolonas.\n\nDosis recomendadas de 100 mg. a 300 mg. por semana.'),
  ('es', 'inyectable', 'trenb-100e'         , 'Trenb 100 E'                  , ' ', ' ', 'trenb-100-e'                  , 'inyectable', '0.00', '/palmera/pub/es/inyectable/trenb-100-e.jpg'                  , '**Trenbolone Enanthate 100 mg.**\n\n**Trenbolone Enanthate** es un esteroide inyectable de accion prolongada, tiene unos efectos positivos promoviendo la sintesis de la proteina, haciendo mejor su absorcion, es un estimulante de el apetito, tiene un alto beneficio disminuyendo los depositos de grasa, esta demostrado que enanthate de trenbolone es un producto que genera fuerza y tamano dando un progreso en la construccion de tejidos del cuerpo, generando asi una calidad impresionante. \n\nEste ester no produce retencion de liquido ni aromatizacion.\n\nDosis recomendas de 75 mg. a 200 mg. por semana.'),
  ('es', 'inyectable', 'testosterone-b250'  , 'Testosterone B250'            , ' ', ' ', 'testosterone-b250'            , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-b250.jpg'            , '**Testosterone Propionate** 30mg\n**Testosterone Phenylpropionate** 60mg\n**Testosterone Isocaproate** 60mg\n**Testosterone Caproate** 100mg\n\nEsta mezcla de testosterone es una combinación de efectos cortos y largos en los niveles de testosterona en el sistema. Se usa para mantener un mejor nivel y una ganancia mucho mayor de masa muscular aumentando los glóbulos rojos y una calidad significativa en cuanto a energía, fuerza y tamaño.\n\nDosis recomendadas de 250 mg. a 500 mg. por semana'),
  ('es', 'inyectable', 'primobolan-d100'    , 'Primobolan D100'              , ' ', ' ', 'primobolan-d100'              , 'inyectable', '0.00', '/palmera/pub/es/inyectable/primobolan-d100.jpg'              , '**Enanthate methenolone** 100 mg.\n\nEl **Primobolan (Enantato Methenolone)** es un producto que no produce aromatización alguna. Es un producto de larga duración y es un esteroide sumamente seguro. Es usado por la mayoría de los físico culturistas entre los ciclos de esteroides para mantener su masa muscular.\n\nDosis recomendadas de 100 mg. a 400 mg. por semana.'),
  ('es', 'inyectable', 'testosterone-m250'  , 'Testosterone M250'            , ' ', ' ', 'testosterone-m250'            , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-m250.jpg'            , '**Testosterone PhenylPropionate** 125 mg.\n**Testosterone Isohexanoate** 125 mg.\n\nEs una mezcla de dos testosteronas combinadas para una mejora en los niveles de testosterona en el sistema, produciendo una alta ganancia muscular pronunciada y fuerza.\n\nDosis recomendadas de 250 mg a 500 mg por semana. '),
  ('es', 'inyectable', 'boldenone-200'      , 'Boldenone 200'                , ' ', ' ', 'boldenone-200'                , 'inyectable', '0.00', '/palmera/pub/es/inyectable/boldenone-200.jpg'                , '**Boldenone undecylenate** 200 mg.\n\nLa **Boldenone Undecylenate** es un anabólico inyectable muy eficaz de uso veterinario. Este compuesto es levemente androgénico. Su aplicación es de una inyección por semana gracias a que tiene una vida media de larga duracion. Con boldenone undecylenate se verán aumento del apetito, calidad de masa muscular y una definición notable gracias a que no produce retención de liquido. Se usa generalmente con testosteronas, trenbolone y winstrol para una ganancia mayor y calidad.\n\nDosis recomendadas 200 mg a 600 mg por semana .'),
  ('es', 'inyectable', 'testosterone-c250'  , 'Testosterone C250'            , ' ', ' ', 'testosterone-c250'            , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-c250.jpg'            , '**Testosterone Cypionate** 250 mg.\n\n**Testosterone Cypionate** es un Ester Inyectable Altamente Androgénico. Con esta testosterona se puede obtener una ganancia considerable de masa muscular y fuerza con un alto grado de retención de liquido, puede producir con facilidad ginecomastia ya que la testosterona convierte con facilidad los estrógenos. este ester es inyectable una vez por semana para mantener los niveles de cypionate en el sistema.\n\nEste ester de testosterona permanece en el sistema por un largo periodo de tiempo.\n\nDosis recomendadas de 200 mg. a 600 mg. por semana.'),
  ('es', 'inyectable', 'decadurabolin-250'  , 'Deca Durabolin 250'           , ' ', ' ', 'deca-durabolin-250'           , 'inyectable', '0.00', '/palmera/pub/es/inyectable/deca-durabolin-250.jpg'           , '**Nandrolone Decanoate** 250 mg.\n\n**Nandrolona Decanoate** es un compuesto inyectable que sin lugar a dudas miligramo por miligramo tiene muchos efectos positivos para el crecimiento muscular y síntesis proteica, estimulación del apetito, producción de glóbulos rojos y aumento de la densidad ósea. Nandrolone decanoate es un anabólico que en altas dosis puede ser altamente androgénico Es usado por muchos atletas con el objetivo de obtención de masa muscular, casi siempre en combinación con testosteronas. Con este compuesto puedes almacenar mas nitrógeno que el que es liberado y un balance positivo en el nitrógeno es sinónimo de crecimiento muscular ya que las células pueden asimilar mas cantidades de proteínas, nandrolone decanoate mantiene una reparación en los tejidos musculares curando temporalmente todos los dolores.\n\nEste compuesto es detectable por mas de un año después de su administración.\n\nDosis recomendadas de 200 mg. a 600 mg. por semana.'),
  ('es', 'inyectable', 'testoviron-300'     , 'Testoviron 300'               , ' ', ' ', 'testoviron-300'               , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testoviron-300.jpg'               , '**Testosterone Propionate** 112 mg.\n**Testosterone Enanthate** 188 mg.\n\n**Testoviron** es una mezcla inyectable de 2 testosteronas (**Enanthate**, **Propionate**) el propionate con una rápida actuación y el enanthate con una duración de dos a tres semanas, estas testosteronas producen un alto nivel estrogenito ya que convierte la testosterona en estrógeno con mucha facilidad dando una gran retención de liquido, fuerza y tamaño muscular, el testoviron se usa en ciclos para obtención de mayor tamaño manteniendo un nivel perfecto de testosterona e incrementando los glóbulos rojos, con este compuesto se pueden desarrollar ginecomastia y otros efectos secundarios.\n\nDosis recomendadas de 200 mg a 600 mg por semana.'),
  ('es', 'inyectable', 'decadurobalin-300'  , 'Deca Durabolin 300'           , ' ', ' ', 'deca-durabolin-300'           , 'inyectable', '0.00', '/palmera/pub/es/inyectable/deca-durabolin-300.jpg'           , '**Nandrolone Decanoate** 300 mg.\n\n**Nandrolona Decanoate** es un compuesto inyectable que sin lugar a dudas miligramo por miligramo tiene muchos efectos positivos para el crecimiento muscular y síntesis proteica, estimulación del apetito, producción de glóbulos rojos y aumento de la densidad ósea. Nandrolone decanoate es un anabólico que en altas dosis puede ser altamente androgénico. Es usado por muchos atletas con el objetivo de obtención de masa muscular, casi siempre en combinación con testosteronas, con este compuesto puedes almacenar mas nitrógeno que el que es liberado y un balance positivo en el nitrógeno es sinónimo de crecimiento muscular ya que las células pueden asimilar mas cantidades de proteínas, nandrolonedecanoate mantiene una reparación en los tejidos musculares curando temporalmente todos los dolores.\n\nEste compuesto es detectable por mas de un año después de su administración.\n\nDosis recomendadas de 200 mg. a 600 mg. por semana.'),
  ('es', 'inyectable', 'testosterone-e300'  , 'Testosterone E300'            , ' ', ' ', 'testosterone-e300'            , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-e300.jpg'            , '**Testosterone Enanthate** 300 mg.\n\n**Enanthate de Testosterone** es por excelencia uno de los esteroides mas usados por los atletas y levantadores de pesas, esta hormona tiene efectos muy positivos en la construcción de masa muscular, es altamente androgénico y un pronunciado visible retención de liquido, este compuesto es usado en hombres de problemas de hipogonadismo (bajos niveles de testosterona) con este ester se obtienen una mayor retención de nitrógeno en las células sinónimo (crecimiento muscular) y una reparación de tejidos dañados, un aumento de los glóbulos rojos, regularmente es usado con ciertos anabólicos en ciclos para obtención de grandes cantidades de masa muscular.\n\nDosis recomendadas de 250 mg a 750 mg por semana.'),
  ('es', 'inyectable', 'bestboldblend-200'  , 'Best Bold Blend 200'          , ' ', ' ', 'best-bold-blend-200'          , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-bold-blend-200.jpg'          , '**Boldenone Acetate** 30 mg.\n**Boldenone Propionate** 50 mg.\n**Boldenone Undecylenate** 100 mg.\n**Boldenone Cyclopentyl propionate (cypionate)** 20 mg.\n\n**Best Bold Blend 200** es un anabolico inyectable muy eficaz de uso veterinario. Este compuesto es levemente androgénico. Su aplicación es de una inyección por semana gracias a que tiene una vida media de larga duración. Con este compuesto se verán aumento del apetito, calidad de masa muscular y una definición notable gracias a que no produce retención de liquido. Se usa generalmente con testosteronas, trenbolone y winstrol para una ganancia mayor y calidad. Este compuesto es para los fisicoculturistas que aman el equipoise.\n\nEsta mezcla proporcionara una definición sin retención de líquidos.\n\nDosis 200 mg. a 600 mg. por semana'),
  ('es', 'inyectable', 'sustanon-350'       , 'Sustanon 350'                 , ' ', ' ', 'sustanon-350'                 , 'inyectable', '0.00', '/palmera/pub/es/inyectable/sustanon-350.jpg'                 , '**Testosterone Acetate** 30 mg.\n**Testosterone Propionate** 60 mg.\n**Testosterone Phenylpropionate** 60 mg.\n**Testosterone Cypionate** 95 mg.\n**Testosterone Decanoate** 105 mg.\n\nEl **Sustanon 350** es una mezcla inyectable, una de las mas usadas por los atletas y levantadores de pesas, ya que ha sido una combinación perfecta y lineal para que el cuerpo obtenga los perfectos niveles de anabolicos. Sustanon 350 es un producto sin lugar a duda de obtención de fuerza y tamaño sólido. Su duración es mucho mayor que el testoviron permaneciendo activo de 3 a 4 semanas, esta mezcla es usada con productos orales, dianabol, anadrol y alguno inyectables, nandrolone decanoate y otros agentes.\n\nDosis recomendadas de 350 mg. a 700 mg. por semana.'),
  ('es', 'inyectable', 'best3nandrolona'    , 'Best 3nandrolona'             , ' ', ' ', 'best-3nandrolona'             , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-3nandrolona.jpg'             , '**Nandrolone Decanoate** 100 mg.\n**Nandrolone Phenylpropionate** 100 mg.\n**Nandrolone Undecanoate 100** mg.\n\n**Best 3nandrolona** es la combinacion para una maximizacion de volumen combinado para un mejor aumento de peso ,obteniendo un mayor apetito y niveles de nandrolone en torrente sanguineo , su uso puede ser combinado con testosteronas y otros.\n\nDosis recomendada de 200mg a 600mg'),
  ('es', 'inyectable', 'testosterone-400'   , 'Testosterone 400'             , ' ', ' ', 'testosterone-400'             , 'inyectable', '0.00', '/palmera/pub/es/inyectable/testosterone-400.jpg'             , '**Testosterone Propionate** 25 mg.\n**Testosterone Cypionate** 187 mg.\n**Testosterone Enanthate** 188 mg.\n\nLa **Testosterone 400** es una excelente mezcla de tres testosteronas, produciendo una combinación de un perfecto nivel de vida de cada producto en el sistema sanguíneo, aunque no lineal estas testosteronas aumentan dramáticamente los glóbulos rojos produciendo una gran fuerza y denotado aumento de peso. \n\nComo todas las testosteronas también produce una gran retención de líquidos y una alta aromatización. \n\nDosis recomendadas de 200 mg. a 800 mg. por semana. '),
  ('es', 'inyectable', 'best3trend'         , 'Best 3Trend'                  , ' ', ' ', 'best-3trend'                  , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-3trend.jpg'                  , '**Trenabolone Acetate** 50 mg.\n**Trenbolone Hexahydrobenzylcarbonate** 50 mg.\n**Trenbolone Enanthate** 100 mg.\n\n**Best 3trend** esta mezcla es una creación para una ganancia neta de masa y disminución de grasa corporal. Bajo este ciclo se obtienen los beneficios mas anhelados y una definición impresionante. \n\nDosis recomendadas 300 mg. por semana. '),
  ('es', 'inyectable', 'bestblend-400'      , 'Best Blend 400'               , ' ', ' ', 'best-blend-400'               , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-blend-400.jpg'               , '**Trenbolone Enanthate** 150 mg.\n**Testosterone Enanthate** 250 mg.\n\n**Best Blend 400** es una mezcla de trenbolone enanthate y testosterone enanthate. Esta mezcla produce una perfecta cantidad de músculo con calidad. Sin lugar a dudas es una combinación muy eficaz para el aumento de unos 5 a 8 kg de masa muscular en tan solo 6 semanas.\n\nDosis recomendadas 400 mg. a 800 mg. por semana .'),
  ('es', 'inyectable', 'bestblend-450'      , 'Best Blend 450'               , ' ', ' ', 'best-blend-450'               , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-blend-450.jpg'               , '**Trenbolone Enanthate** 150 mg.\n**Testosterone Enanthate** 250 mg.\n**Testosterone Propionate** 50 mg.\n\n**Best Blend 450** is a blend of 2 testosterones, one of which with a short average life (propionate) and a long lasting one (enathate) that combined with trembolone offers an extremely good level of anabolics in the blood system. This combination is perfect for obtaining a loto f well defined mass and good quality. With this compound you can get up to 8 kgs of mass in 6 weeks.\n\nRecommended Doses of 450 mg. to 900 mg. per week'),
  ('es', 'inyectable', 'bestblend-500'      , 'Best Blend 500'               , ' ', ' ', 'best-blend-500'               , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-blend-500.jpg'               , '**Boldenone Undecylenate** 200 mg.\n**Testosterone Enanthate** 100 mg.\n**Testosterone Cypionate** 100 mg.\n**Trenbolone Enanthate** 100 mg.\n\n**Best Blend 500** es la mezcla de cuatro compuestos combinados perfectamente y lineales, para añadir al cuerpo una cantidad extrema de masa muscular y un tamaño bien definido. \n\nDosis recomendada de 500 mg. a 1000 mg. por semana. '),
  ('es', 'inyectable', 'bestblend-600'      , 'Best Blend 600'               , ' ', ' ', 'best-blend-600'               , 'inyectable', '0.00', '/palmera/pub/es/inyectable/best-blend-600.jpg'               , '**Testosterone Cypionate** 200 mg.\n**Boldenone Undecylenate** 200 mg.\n**Nandrolone Decanoate** 200 mg.\n\n**Best Blend 600** es una mezcla de productos excelentes los cuales se combinan dos anabólicos y un androgénico para la obtención de una ganancia de peso considerable y una muy buena calidad. Este compuesto es inyectable una o dos veces por semanas según sus necesidades.\n\nDosis recomendadas 600 mg. a 1200 mg. por semana.'),
  ('en', 'nuevo'     , 'winstrol-100'       , 'Winstrol 100'                 , ' ', ' ', 'winstrol-100'                 , 'new'       , '0.00', '/palmera/pub/en/new/winstrol-100.jpg'                        , '**Stanzolol** 100 mg.\n\n**Stanozolol** is an inyectable compound that isused for “cutting” usually combined with tenbolone or halotestin, produces excellent results in exit cycles to hide or conceal liquid retention of the testosterones. \n\nRecommended doses 50 mg. Every 3 days .'),
  ('en', 'nuevo'     , 'winstrol-oilbase100', 'Winstrol Oil Base 100'        , ' ', ' ', 'winstrol-oil-base-100'        , 'new'       , '0.00', '/palmera/pub/en/new/winstrol-oil-base-100.jpg'               , '**Stanozolol** 100 mg'),
  ('en', 'nuevo'     , 'masteron-100'       , 'Masteron 100'                 , ' ', ' ', 'masteron-100'                 , 'new'       , '0.00', '/palmera/pub/en/new/masteron-100.jpg'                        , '**Drostalone Propionate** 100mg.'),
  ('en', 'nuevo'     , 'dianabol-50'        , 'Dianabol 50'                  , ' ', ' ', 'dianabol-50'                  , 'new'       , '0.00', '/palmera/pub/en/new/dianabol-50.jpg'                         , '**Methandrostenolone** 50mg.'),
  ('en', 'nuevo'     , 'bestblend-4test'    , 'Best Blend 4Test'             , ' ', ' ', 'best-blend-4test'             , 'new'       , '0.00', '/palmera/pub/en/new/best-blend-4test.jpg'                    , '**Trenbolone Acetate** 100mg.\n**Drostanolone Propionate (Masteron)** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Testosterone Propionate** 100mg.\n'),
  ('en', 'nuevo'     , 'bestblend-400t'     , 'Best Blend 400 T'             , ' ', ' ', 'best-blend-400-t'             , 'new'       , '0.00', '/palmera/pub/en/new/best-blend-400-t.jpg'                    , '**Trenbolone Acetate** 100mg.\n**Testosterone Cypionate** 200mg.\n**Boldenone Undecylenate** 100mg.'),
  ('en', 'nuevo'     , 'bestblend-500t'     , 'Best Blend 500 T'             , ' ', ' ', 'best-blend-500-t'             , 'new'       , '0.00', '/palmera/pub/en/new/best-blend-500-t.jpg'                    , '**Trenbolone Acetate** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Testosterone Cypionate** 200mg.\n**Trenbolone Enanthate** 100mg.\n'),
  ('en', 'nuevo'     , 'bestblend-400b'     , 'Best Blend 400 B'             , ' ', ' ', 'best-blend-400-b'             , 'new'       , '0.00', '/palmera/pub/en/new/best-blend-400-b.jpg'                    , '**Testosterone Propionate** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Trenbolone Acetate** 100mg.\n**Testosterone Acetate** 100mg.'),
  ('en', 'nuevo'     , 'bestblend-3test'    , 'Best Blend 3test'             , ' ', ' ', 'best-blend-3test'             , 'new'       , '0.00', '/palmera/pub/en/new/best-blend-3test.jpg'                    , '**Testosterone Propionate** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Trenbolone Acetate** 100mg.\n**Testosterone Acetate** 100mg.'),
  ('es', 'nuevo'     , 'winstrol-100'       , 'Winstrol 100'                 , ' ', ' ', 'winstrol-100'                 , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/winstrol-100.jpg'                      , '**Stanzolol** 100 mg.\n\n**Stanozolol** es un compuesto inyectable que se utiliza para corte usualmente combinado con trenbolone o halotestin, produce excelentes resultados en salida de ciclos para ocultar o disimular la retención de líquidos de las testosteronas. produciendo asi un aspecto duro y definido.\n\nDosis recomendada 50 mg. cada 3 dias.'),
  ('es', 'nuevo'     , 'winstrol-oilbase100', 'Winstrol Oil Base 100'        , ' ', ' ', 'winstrol-oil-base-100'        , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/winstrol-oil-base-100.jpg'             , '**Stanozolol** 100 mg'),
  ('es', 'nuevo'     , 'masteron-100'       , 'Masteron 100'                 , ' ', ' ', 'masteron-100'                 , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/masteron-100.jpg'                      , '**Drostalone Propionate** 100mg.'),
  ('es', 'nuevo'     , 'dianabol-50'        , 'Dianabol 50'                  , ' ', ' ', 'dianabol-50'                  , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/dianabol-50.jpg'                       , '**Methandrostenolone** 50mg.'),
  ('es', 'nuevo'     , 'bestblend-4test'    , 'Best Blend 4Test'             , ' ', ' ', 'best-blend-4test'             , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/best-blend-4test.jpg'                  , '**Trenbolone Acetate** 100mg.\n**Drostanolone Propionate (Masteron)** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Testosterone Propionate** 100mg.\n'),
  ('es', 'nuevo'     , 'bestblend-400t'     , 'Best Blend 400 T'             , ' ', ' ', 'best-blend-400-t'             , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/best-blend-400-t.jpg'                  , '**Trenbolone Acetate** 100mg.\n**Testosterone Cypionate** 200mg.\n**Boldenone Undecylenate** 100mg.'),
  ('es', 'nuevo'     , 'bestblend-500t'     , 'Best Blend 500 T'             , ' ', ' ', 'best-blend-500-t'             , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/best-blend-500-t.jpg'                  , '**Trenbolone Acetate** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Testosterone Cypionate** 200mg.\n**Trenbolone Enanthate** 100mg.\n'),
  ('es', 'nuevo'     , 'bestblend-400b'     , 'Best Blend 400 B'             , ' ', ' ', 'best-blend-400-b'             , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/best-blend-400-b.jpg'                  , '**Testosterone Propionate** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Trenbolone Acetate** 100mg.\n**Testosterone Acetate** 100mg.'),
  ('es', 'nuevo'     , 'bestblend-3test'    , 'Best Blend 3test'             , ' ', ' ', 'best-blend-3test'             , 'nuevo'     , '0.00', '/palmera/pub/es/nuevo/best-blend-3test.jpg'                  , '**Testosterone Propionate** 100mg.\n**Boldenone Undecylenate** 100mg.\n**Trenbolone Acetate** 100mg.');
/**
 * @author Hector Menendez <h@cun.mx>
 * @licence http://etor.mx/licence.txt
 * @created 2011/SEP/19 13:26
 */
DROP TABLE IF EXISTS `stock`;
CREATE TABLE `stock`(
  `id`         CHAR(16) NOT NULL,
  `product` VARCHAR(44) NOT NULL,
  `created`    DATETIME NOT NULL,
  `expires`    DATETIME NOT NULL,
  `valided`  TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `printed`  TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`id`),
  INDEX(`product`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/**
 * @author Hector Menendez <h@cun.mx>
 * @licence http://etor.mx/licence.txt
 * @created 2011/SEP/21 15:00
 */
DROP TABLE IF EXISTS `static`;
CREATE TABLE `static`(
  `id`         INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(12) NOT NULL,
  `lang`      CHAR(2) NOT NULL,
  `name`  VARCHAR(24) NOT NULL,
  `url`   VARCHAR(24) NOT NULL,
  `keyw` VARCHAR(300) NOT NULL,
  `desc` VARCHAR(300) NOT NULL,
  PRIMARY KEY(`id`),
  INDEX(`class`),
  INDEX(`url`),
  INDEX(`lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
INSERT INTO `static` (`lang`,`class`,`name`,`url`,`keyw`,`desc`) VALUES
 ('en', 'products'  , 'products'    , 'products'     , ' '  , ' '),
 ('en', 'authentic' , 'authenticity', 'authenticity' , ' '  , ' '),
 ('en', 'about-us'  , 'about us'    , 'about-us'     , ' '  , ' '),
 ('en', 'contact-us', 'contact us'  , 'contact-us'   , ' '  , ' '),
 ('es', 'products'  , 'productos'   , 'productos'    , ' '  , ' '),
 ('es', 'authentic' , 'autenticidad', 'autenticidad' , ' '  , ' '),
 ('es', 'about-us'  , 'nosotros'    , 'nosotros'     , ' '  , ' '),
 ('es', 'contact-us', 'contacto'    , 'contacto'     , ' '  , ' ')
;